= Data Protection - GDPR - Retention Periods

:toc:
:toclevels: 4

<<<

.Document information
[%autowidth]
|===
| | 
|Classification:
|restricted
|Author:
|DPO
|===

== Retention Periods in General ==
 
Orientation for retetion periods is the respective regulation for the statue of limitation. There are basic data retention periods defined in VONQ's Data Management Policy: https://docs.google.com/document/d/1FCY1sSlBngdHullFN6PwC-3NH5--b4Nu[]

=== VONQ Job Post ===

Once job postings (vacancies) are deactivated or become inactive:
- Descriptions of deactivated vacancies: 12 months
- metadata of deactivated vacancies: 24 months

In General:
Log files of job board interactions (meta data): 12 months
payload logs from transactions to job boards: 30 days

Apart from that retention periods are defined by the statue of limitation in the Netherlands.

Example how to mention: link: https://docs.google.com/spreadsheets/d/1EN5KEp2W-orTVisQsXTF60v7rhUIcxab/edit?gid=201001863#gid=201001863[]

=== VONQ HAPI ===

TODO

=== VONQ JMP ===

TODO

=== VONQ Kopilot ===

TODO