= Data Protection - GDPR - Internal Resources - Sub-Processor notification examples

:toc:
:toclevels: 4

<<<

.Document information
|===
| | 
|Classification:
|public
|Author:
|DPO
|Last changed:
|30.05.2025
|===

== Notification examples ==

=== Google (GCP) ===

Hello GCP Customer,

We are writing to let you know about the following updates to the Third-Party Subprocessors we engage for Google Cloud:

We are adding LXT AI Romania S.R.L for the Speech to Text Service.
No action is required on your part.

You can find information about the tasks our Subprocessors perform on our Google Cloud Platform Subprocessors list.

Thanks for choosing Google Cloud.

=== Osano ===

Dear Osano Customer, 

As part of Osano’s commitment to delivering you excellent service, we are adding replacing Chargebee  with Stripe as a subprocessor in our customer billing processes. Our complete list of subprocessors can be found here (insert link).
 
Because Stripe may process your organization’s “Personal Data” (as defined under the General Data Protection Regulation (GDPR)) in connection with the services and products that Osano provides, this communication shall serve as notification that Stripe will be a replacement subprocessor. Please note that Stripe is already an existing sub-processor that we use to facilitate payments. 
 
How Osano will be using Stripe
Osano will be using Stripe to facilitate payment when customers are purchasing our offerings. 
 
How Personal Data will be protected 
All information from or about Osano customers is considered confidential and will be maintained in accordance with the terms of our agreements with Stripe. 

Stripe has a number of certifications and maintains robust controls designed to protect data and keep it secure, as detailed here (insert link).

Further, Stripe will only process any data that it receives from Osano in accordance with Osano’s instructions, will maintain appropriate technical, organizational and administrative controls, will support any privacy rights requests, and Stripe will notify Osano without undue delay of any security incident. 
 
Next Steps 
Pursuant to our agreement with you, and in accordance with relevant data protection regulations, you have the right to object to the use of Stripe as a replacement subprocessor.   
 
If you do, you must provide written notice to us within 30 days of this notice. If you choose to object or have any other questions, please reach out to us at mailto:legal@osano.com[legal@osano.com] and we will be glad to assist you with your request.  
 
If you don’t object to Stripe as a new subprocessor, no further action is required and  within 30 days of this notice, you will be deemed to have consented to Stripe’s use. 
 
Thank you,
The Osano Team

